<?php
/**
 * TPT Aggregator — One-shot web installer
 *
 *   Place these alongside the codebase, then visit  http://your-domain/public/setup.php
 *
 *   Steps:  Preflight  →  DB credentials  →  App config  →  Confirm + Install  →  Done
 *
 *   Once finished, this file refuses to run again unless you remove
 *   `writable/.installed` from the project root. For maximum safety, delete
 *   `public/setup.php` after a successful install.
 *
 *   Single file, zero framework dependencies for Steps 1–3. Step 4 (Install)
 *   bootstraps CodeIgniter once the .env file has been written.
 */

declare(strict_types=1);
session_start();
ini_set('display_errors', '1');
error_reporting(E_ALL);

$ROOT       = dirname(__DIR__);
$ENV_PATH   = $ROOT . '/.env';
$ENV_SAMPLE = $ROOT . '/env';
$LOCK_PATH  = $ROOT . '/writable/.installed';
$DB_DUMP    = $ROOT . '/database.sql';

// ───────────────────────────────────────── Helpers ─────────────────────────────────────────

function h(string $s): string { return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function url(int $step, array $extra = []): string {
    $extra['step'] = $step;
    return basename(__FILE__) . '?' . http_build_query($extra);
}
function flash(string $kind, string $msg): void { $_SESSION['_flash'][] = [$kind, $msg]; }
function pop_flash(): array { $f = $_SESSION['_flash'] ?? []; $_SESSION['_flash'] = []; return $f; }

function pdo_connect(string $host, string $port, string $user, string $pass, ?string $db = null): \PDO
{
    $dsn = "mysql:host={$host};port={$port}" . ($db ? ";dbname={$db}" : '') . ';charset=utf8mb4';
    return new \PDO($dsn, $user, $pass, [
        \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
        \PDO::ATTR_PERSISTENT => false,
    ]);
}

function write_root_htaccess(string $path): bool
{
    $content = <<<'HT'
# Generated by public/setup.php
# Rewrites every request to /public/ so the bare domain serves CodeIgniter
# without "/public/" in the URL. Delete this file if your web-server
# DocumentRoot already points at /public/.
DirectoryIndex public/index.php

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/public/
    RewriteRule ^(.*)$ public/$1 [L]
</IfModule>

# Block direct HTTP access to sensitive project files.
<FilesMatch "^(\.env|\.env\..*|composer\.json|composer\.lock|spark|preload\.php|phpunit\.xml\.dist|database\.sql|README\.md|INSTALL\.md|USER-GUIDE\.md|FEATURES\.md|LICENSE)$">
    Require all denied
</FilesMatch>
RedirectMatch 404 ^/(app|tests|tools|writable|vendor|builds)(/.*)?$
HT;
    return @file_put_contents($path, $content) !== false;
}

function write_env(string $envPath, array $cfg, string $sampleEnv): bool
{
    // Prefer copying from `env` (the CI4 sample) and overwriting our keys
    $template = is_file($sampleEnv) ? file_get_contents($sampleEnv) : '';
    if (!is_string($template) || $template === '') {
        // Build a minimal template
        $template = "CI_ENVIRONMENT = production\n\n"
            . "app.baseURL = ''\n"
            . "database.default.hostname = 127.0.0.1\n"
            . "database.default.database = \n"
            . "database.default.username = \n"
            . "database.default.password = \n"
            . "database.default.DBDriver = MySQLi\n"
            . "database.default.port = 3306\n\n"
            . "encryption.key = \n";
    }

    $set = function (string $contents, string $key, string $value) {
        $line  = $key . ' = ' . (preg_match('/\s/', $value) || $value === '' ? "'" . str_replace("'", "\\'", $value) . "'" : $value);
        // Match: optional `# `, key, optional spaces, =, anything until EOL
        $pattern = '/^[#\s]*' . preg_quote($key, '/') . '\s*=\s*.*$/m';
        if (preg_match($pattern, $contents)) {
            return preg_replace($pattern, $line, $contents, 1);
        }
        return rtrim($contents) . "\n" . $line . "\n";
    };

    $template = $set($template, 'CI_ENVIRONMENT',           $cfg['env']);
    $template = $set($template, 'app.baseURL',              $cfg['baseUrl']);
    $template = $set($template, 'app.indexPage',            '');
    $template = $set($template, 'app.forceGlobalSecureRequests', $cfg['https'] ? 'true' : 'false');
    $template = $set($template, 'database.default.hostname',$cfg['db_host']);
    $template = $set($template, 'database.default.port',    $cfg['db_port']);
    $template = $set($template, 'database.default.database',$cfg['db_name']);
    $template = $set($template, 'database.default.username',$cfg['db_user']);
    $template = $set($template, 'database.default.password',$cfg['db_pass']);
    $template = $set($template, 'database.default.DBDriver','MySQLi');
    $template = $set($template, 'encryption.key',           $cfg['enc_key']);
    $template = $set($template, 'tpt.appName',              $cfg['app_name']);
    $template = $set($template, 'tpt.companyName',          $cfg['company_name']);

    return file_put_contents($envPath, $template) !== false;
}

function preflight(): array
{
    global $ROOT;
    $checks = [];
    $checks[] = ['PHP version ≥ 8.2', PHP_VERSION_ID >= 80200, PHP_VERSION];
    foreach (['mysqli','pdo_mysql','mbstring','intl','curl','openssl','json','fileinfo'] as $ext) {
        $checks[] = ["Extension: $ext", extension_loaded($ext), extension_loaded($ext) ? 'loaded' : 'MISSING'];
    }
    foreach ([
        'writable/'             => $ROOT . '/writable',
        'writable/cache/'       => $ROOT . '/writable/cache',
        'writable/session/'     => $ROOT . '/writable/session',
        'writable/uploads/'     => $ROOT . '/writable/uploads',
        'writable/logs/'        => $ROOT . '/writable/logs',
        'public/uploads/'       => $ROOT . '/public/uploads',
        '.env writable folder'  => $ROOT,
    ] as $label => $dir) {
        if (!is_dir($dir)) @mkdir($dir, 0775, true);
        $checks[] = [$label . ' writable', is_dir($dir) && is_writable($dir), $dir];
    }
    $checks[] = ['vendor/autoload.php present', is_file($ROOT . '/vendor/autoload.php'), $ROOT . '/vendor/autoload.php'];
    $checks[] = ['app/Database/Migrations present', is_dir($ROOT . '/app/Database/Migrations'), $ROOT . '/app/Database/Migrations'];
    return $checks;
}

function preflight_ok(array $checks): bool { foreach ($checks as $c) if (!$c[1]) return false; return true; }

function gen_encryption_key(): string { return 'hex2bin:' . bin2hex(random_bytes(32)); }

function bootstrap_codeigniter(string $ROOT): \CodeIgniter\CodeIgniter
{
    $_SERVER['HTTP_HOST']     = $_SERVER['HTTP_HOST'] ?? 'localhost';
    $_SERVER['REQUEST_URI']   = '/';
    $_SERVER['SCRIPT_NAME']   = '/index.php';
    $_SERVER['REQUEST_METHOD']= 'GET';

    chdir($ROOT);
    require_once $ROOT . '/app/Config/Paths.php';
    require_once $ROOT . '/system/bootstrap.php';

    $app = \Config\Services::codeigniter();
    $app->initialize();
    return $app;
}

function run_migrations(string $ROOT): array
{
    bootstrap_codeigniter($ROOT);
    $runner = \Config\Services::migrations();
    try {
        $runner->latest();
        return ['ok' => true, 'msg' => 'Migrations applied.'];
    } catch (\Throwable $e) {
        return ['ok' => false, 'msg' => $e->getMessage()];
    }
}

function run_seeders(string $ROOT, array $seeders): array
{
    bootstrap_codeigniter($ROOT);
    $seeder = \Config\Database::seeder();
    $applied = [];
    foreach ($seeders as $name) {
        try { $seeder->call($name); $applied[] = $name; }
        catch (\Throwable $e) { return ['ok' => false, 'msg' => "Seeder $name failed: " . $e->getMessage(), 'applied' => $applied]; }
    }
    return ['ok' => true, 'applied' => $applied];
}

function import_sql_dump(\PDO $pdo, string $sqlFile): array
{
    if (!is_file($sqlFile)) return ['ok' => false, 'msg' => 'database.sql not found in project root.'];

    $sql = file_get_contents($sqlFile);
    if ($sql === false) return ['ok' => false, 'msg' => 'Could not read database.sql'];

    // Split on semicolon at end-of-line. mysqldump output is well-behaved;
    // a more robust split would respect quoted strings, but mysqldump rarely
    // produces those at end-of-line.
    $statements = preg_split('/;\s*\n/', $sql);
    $count = 0;
    $pdo->exec("SET FOREIGN_KEY_CHECKS=0");
    foreach ($statements as $stmt) {
        $stmt = trim($stmt);
        if ($stmt === '' || strpos($stmt, '--') === 0) continue;
        try { $pdo->exec($stmt); $count++; }
        catch (\Throwable $e) {
            $pdo->exec("SET FOREIGN_KEY_CHECKS=1");
            return ['ok' => false, 'msg' => 'Failed: ' . substr($e->getMessage(), 0, 300) . ' on: ' . substr($stmt, 0, 200)];
        }
    }
    $pdo->exec("SET FOREIGN_KEY_CHECKS=1");
    return ['ok' => true, 'count' => $count];
}

function ensure_super_admin(\PDO $pdo, string $email, string $password, string $name): array
{
    // Find or create — admin role first
    $email = strtolower(trim($email));
    if (!filter_var($email, FILTER_VALIDATE_EMAIL)) return ['ok' => false, 'msg' => 'Invalid email'];

    $roleId = (int) ($pdo->query("SELECT id FROM roles WHERE role_key = 'admin' LIMIT 1")->fetchColumn() ?: 0);
    if (!$roleId) {
        // Try any role
        $roleId = (int) ($pdo->query("SELECT id FROM roles ORDER BY id ASC LIMIT 1")->fetchColumn() ?: 0);
    }
    if (!$roleId) return ['ok' => false, 'msg' => 'No roles in database — run migrations + permission seeder first.'];

    $stmt = $pdo->prepare("SELECT id FROM users WHERE email = ? LIMIT 1");
    $stmt->execute([$email]);
    $userId = (int) ($stmt->fetchColumn() ?: 0);

    $hash = password_hash($password, PASSWORD_BCRYPT);
    if ($userId) {
        $up = $pdo->prepare("UPDATE users SET password_hash = ?, name = ?, role_id = ?, status = 1, is_super_admin = 1, updated_at = NOW() WHERE id = ?");
        $up->execute([$hash, $name, $roleId, $userId]);
    } else {
        $ins = $pdo->prepare("INSERT INTO users (role_id, name, email, mobile, password_hash, status, is_super_admin, created_at, updated_at) VALUES (?, ?, ?, '', ?, 1, 1, NOW(), NOW())");
        $ins->execute([$roleId, $name, $email, $hash]);
        $userId = (int) $pdo->lastInsertId();
    }
    return ['ok' => true, 'user_id' => $userId];
}

// ─────────────────────────────────────── Already-installed gate ───────────────────────────────────────

if (file_exists($LOCK_PATH) && empty($_GET['force'])) {
    ?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Already installed · TPT</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    </head><body class="bg-light"><div class="container py-5" style="max-width:640px;">
    <div class="card"><div class="card-body p-4">
      <h3>Already installed</h3>
      <p class="text-muted">A lock file exists at <code><?= h($LOCK_PATH) ?></code>. Setup will not run again.</p>
      <p>If you really want to re-run setup, delete that file and visit setup again.</p>
      <p class="mt-4"><a class="btn btn-primary" href="<?= h(rtrim(dirname($_SERVER['REQUEST_URI']), '/')) ?>/login">Go to sign-in →</a></p>
      <p class="text-muted mt-2"><small>For your security, please <strong>delete this file</strong> (<code>public/setup.php</code>) once installation is verified working.</small></p>
    </div></div></div></body></html><?php
    exit;
}

// ─────────────────────────────────────── Step routing ───────────────────────────────────────

$step = isset($_GET['step']) ? max(1, min(5, (int) $_GET['step'])) : 1;

if ($step === 4 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    // Final install run
    $cfg = $_SESSION['cfg'] ?? [];
    if (empty($cfg)) { flash('error', 'Session expired — start over.'); header('Location: ' . url(1)); exit; }

    // 1. Connect to DB (and create if asked)
    try {
        $pdo = pdo_connect($cfg['db_host'], $cfg['db_port'], $cfg['db_user'], $cfg['db_pass']);
        $exists = $pdo->query("SHOW DATABASES LIKE " . $pdo->quote($cfg['db_name']))->fetchColumn();
        if (!$exists) {
            $pdo->exec("CREATE DATABASE `{$cfg['db_name']}` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        }
        $pdo->exec("USE `{$cfg['db_name']}`");
    } catch (\Throwable $e) {
        flash('error', 'DB connect failed: ' . $e->getMessage());
        header('Location: ' . url(2)); exit;
    }

    // 2. Write .env
    if (!write_env($ENV_PATH, $cfg, $ENV_SAMPLE)) {
        flash('error', 'Could not write .env to ' . $ENV_PATH . '. Check folder permissions.');
        header('Location: ' . url(3)); exit;
    }

    // 2b. Optionally drop a project-root .htaccess so the bare domain serves
    //     /public/ — no /public/ prefix in the URL the user sees.
    if (!empty($cfg['install_htaccess'])) {
        $htOk = write_root_htaccess($ROOT . '/.htaccess');
        flash($htOk ? 'success' : 'warning',
            $htOk ? 'Project-root .htaccess installed — clean URLs enabled (no /public/ prefix).'
                  : 'Could not write .htaccess at project root. Drop the bundled .htaccess there manually.');
    }

    // 3. Either restore SQL dump OR run migrations + seeders
    $log = [];
    if (!empty($cfg['use_dump']) && is_file($DB_DUMP)) {
        $log[] = ['Restoring database.sql', null];
        $r = import_sql_dump($pdo, $DB_DUMP);
        if (!$r['ok']) { flash('error', 'Restore failed: ' . $r['msg']); header('Location: ' . url(3)); exit; }
        $log[count($log) - 1][1] = "OK ({$r['count']} statements)";
    } else {
        $log[] = ['Running migrations', null];
        $r = run_migrations($ROOT);
        if (!$r['ok']) { flash('error', 'Migrate failed: ' . $r['msg']); header('Location: ' . url(3)); exit; }
        $log[count($log) - 1][1] = $r['msg'];

        $log[] = ['Running seeders', null];
        $r = run_seeders($ROOT, ['PermissionSeeder', 'TripExpenseCategorySeeder', 'EmailTemplateSeeder']);
        if (!$r['ok']) { flash('error', 'Seed failed: ' . $r['msg']); header('Location: ' . url(3)); exit; }
        $log[count($log) - 1][1] = 'Applied: ' . implode(', ', $r['applied']);
    }

    // 4. Create super admin
    $log[] = ['Creating super-admin user', null];
    $r = ensure_super_admin($pdo, $cfg['admin_email'], $cfg['admin_pass'], $cfg['admin_name']);
    if (!$r['ok']) { flash('error', 'Admin create failed: ' . $r['msg']); header('Location: ' . url(3)); exit; }
    $log[count($log) - 1][1] = 'User #' . $r['user_id'] . ' (super-admin)';

    // 5. Lock file
    @file_put_contents($LOCK_PATH, date('c') . ' installed by ' . ($_SERVER['REMOTE_ADDR'] ?? 'unknown'));
    $log[] = ['Wrote lock file', $LOCK_PATH];

    $_SESSION['install_log'] = $log;
    $_SESSION['install_done'] = true;
    header('Location: ' . url(5));
    exit;
}

// Capture form posts for steps 2 & 3
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $cfg = $_SESSION['cfg'] ?? [];
    foreach ($_POST as $k => $v) $cfg[$k] = is_string($v) ? trim($v) : $v;

    if ($step === 2) {
        $needed = ['db_host','db_port','db_user','db_name'];
        foreach ($needed as $n) if (!isset($cfg[$n]) || $cfg[$n] === '') { flash('error', "$n is required"); break; }
        if (!isset($_SESSION['_flash']) || empty($_SESSION['_flash'])) {
            // Test connection
            try {
                $pdo = pdo_connect($cfg['db_host'], $cfg['db_port'], $cfg['db_user'], $cfg['db_pass'] ?? '');
                $exists = $pdo->query("SHOW DATABASES LIKE " . $pdo->quote($cfg['db_name']))->fetchColumn();
                $cfg['db_exists'] = $exists ? 1 : 0;
                $_SESSION['cfg'] = $cfg;
                header('Location: ' . url(3)); exit;
            } catch (\Throwable $e) { flash('error', 'Connection failed: ' . $e->getMessage()); }
        }
        $_SESSION['cfg'] = $cfg;
    }
    if ($step === 3) {
        if (empty($cfg['enc_key'])) $cfg['enc_key'] = gen_encryption_key();
        if (empty($cfg['baseUrl']))     { flash('error', 'Base URL is required'); }
        if (empty($cfg['admin_email']) || !filter_var($cfg['admin_email'], FILTER_VALIDATE_EMAIL)) flash('error', 'Valid super-admin email required');
        if (empty($cfg['admin_pass']) || strlen($cfg['admin_pass']) < 8) flash('error', 'Super-admin password must be at least 8 characters');
        if (empty($cfg['app_name']))      $cfg['app_name'] = 'TPT Aggregator';
        if (empty($cfg['company_name']))  $cfg['company_name'] = 'TPT Logistics';
        if (empty($cfg['admin_name']))    $cfg['admin_name'] = 'System Admin';
        if (empty($cfg['env']))           $cfg['env'] = 'production';
        if (!isset($cfg['https']))        $cfg['https'] = '';
        if (!isset($cfg['use_dump']))     $cfg['use_dump'] = '';
        $_SESSION['cfg'] = $cfg;
        if (empty($_SESSION['_flash'])) { header('Location: ' . url(4)); exit; }
    }
}

$preflight = preflight();
$flashes   = pop_flash();
$cfg       = $_SESSION['cfg'] ?? [];

// ─────────────────────────────────────── HTML ───────────────────────────────────────
?><!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow">
<title>TPT Aggregator · Setup · Step <?= $step ?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<style>
  body { background:#f4f4f4; font-family: -apple-system, system-ui, "Segoe UI", Roboto, sans-serif; }
  .wrap { max-width: 760px; margin: 2rem auto; padding: 0 1rem; }
  .stepper { display:flex; gap:.5rem; margin-bottom:1.5rem; flex-wrap:wrap; }
  .stepper .pill { padding:.4rem .8rem; border-radius:999px; background:#e9e9e9; color:#777; font-size:.82rem; }
  .stepper .pill.active { background:#1a1a1a; color:#fff; }
  .stepper .pill.done   { background:#27ae60; color:#fff; }
  .preflight { font-family: ui-monospace, "JetBrains Mono", monospace; font-size:.85rem; background:#0e1218; color:#cdd0d4; border-radius:6px; padding:1rem; }
  .preflight .ok   { color:#7be084; }
  .preflight .bad  { color:#ff7a7a; }
</style>
</head><body>
<div class="wrap">

  <h2 class="mb-1">TPT Aggregator — Installer</h2>
  <p class="text-muted">Five small steps. Once finished, delete <code>public/setup.php</code>.</p>

  <div class="stepper">
    <?php foreach ([1=>'Preflight', 2=>'Database', 3=>'App config', 4=>'Install', 5=>'Done'] as $i => $lbl): ?>
      <span class="pill <?= $i < $step ? 'done' : ($i === $step ? 'active' : '') ?>"><?= $i ?>. <?= h($lbl) ?></span>
    <?php endforeach; ?>
  </div>

  <?php foreach ($flashes as [$kind, $msg]): ?>
    <div class="alert alert-<?= $kind === 'error' ? 'danger' : 'success' ?>"><?= h($msg) ?></div>
  <?php endforeach; ?>

  <div class="card"><div class="card-body p-4">

  <?php if ($step === 1): ?>
    <h4>Preflight checks</h4>
    <p class="text-muted">Verifying your server has everything needed.</p>
    <div class="preflight">
      <?php foreach ($preflight as $c): ?>
        <div><span class="<?= $c[1] ? 'ok' : 'bad' ?>"><?= $c[1] ? '✓' : '✗' ?></span> <?= h($c[0]) ?> <span class="text-muted">— <?= h((string) $c[2]) ?></span></div>
      <?php endforeach; ?>
    </div>
    <div class="mt-4 d-flex gap-2">
      <a class="btn btn-primary <?= preflight_ok($preflight) ? '' : 'disabled' ?>" href="<?= h(url(2)) ?>">Next →</a>
      <a class="btn btn-light" href="<?= h(url(1)) ?>">Re-check</a>
    </div>
    <?php if (!preflight_ok($preflight)): ?>
      <p class="text-muted mt-3" style="font-size:.85rem;">Fix the failing items above (install missing extensions, chmod folders to 0775, install Composer dependencies with <code>composer install</code>) and re-run.</p>
    <?php endif; ?>

  <?php elseif ($step === 2): ?>
    <h4>Database</h4>
    <p class="text-muted">If the database doesn't exist, the installer will create it. The user must have <code>CREATE</code> + <code>ALTER</code> privileges.</p>
    <form method="post" action="<?= h(url(2)) ?>">
      <div class="row g-3">
        <div class="col-md-7"><label class="form-label">Host *</label>
          <input class="form-control" name="db_host" value="<?= h($cfg['db_host'] ?? '127.0.0.1') ?>" required></div>
        <div class="col-md-5"><label class="form-label">Port *</label>
          <input class="form-control" name="db_port" value="<?= h($cfg['db_port'] ?? '3306') ?>" required></div>
        <div class="col-md-7"><label class="form-label">Database name *</label>
          <input class="form-control" name="db_name" value="<?= h($cfg['db_name'] ?? 'tpt_db') ?>" required></div>
        <div class="col-md-5"><label class="form-label">User *</label>
          <input class="form-control" name="db_user" value="<?= h($cfg['db_user'] ?? 'root') ?>" required></div>
        <div class="col-12"><label class="form-label">Password</label>
          <input type="password" class="form-control" name="db_pass" value="<?= h($cfg['db_pass'] ?? '') ?>"></div>
      </div>
      <div class="mt-4 d-flex gap-2">
        <button class="btn btn-primary">Test connection &amp; continue →</button>
        <a class="btn btn-light" href="<?= h(url(1)) ?>">← Back</a>
      </div>
    </form>

  <?php elseif ($step === 3): ?>
    <h4>Application config</h4>
    <form method="post" action="<?= h(url(3)) ?>">
      <h6 class="mt-3 mb-2 text-muted">Application</h6>
      <div class="row g-3">
        <?php
        // Smart baseURL default: strip /public/setup.php so the suggestion is the
        // bare project URL (which works once the project-root .htaccess rewrites
        // every request to /public/). Falls back to stripping just /setup.php.
        $proto   = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://';
        $host    = $_SERVER['HTTP_HOST'] ?? 'localhost';
        $uri     = (string) ($_SERVER['REQUEST_URI'] ?? '/');
        $path    = preg_replace('#/public/setup\.php.*$#', '/', $uri);
        if ($path === $uri) $path = str_replace('/setup.php', '/', $uri);
        $smartDefault = $proto . $host . $path;
        ?>
        <div class="col-md-7"><label class="form-label">Base URL *</label>
          <input class="form-control" name="baseUrl" placeholder="https://tpt2.osob.in/" value="<?= h($cfg['baseUrl'] ?? $smartDefault) ?>" required>
          <div class="form-text" style="font-size:.78rem;">
            The public URL of your app, with a trailing <code>/</code>.
            Used in every email link, the driver PWA URL, vendor quote links, etc.
            Leave the <strong>"Install project-root .htaccess"</strong> box ticked below to drop the
            <code>/public/</code> from this URL.
          </div>
        </div>
        <div class="col-md-5"><label class="form-label">Environment</label>
          <select class="form-select" name="env">
            <option value="production"  <?= ($cfg['env'] ?? 'production') === 'production' ? 'selected' : '' ?>>production</option>
            <option value="development" <?= ($cfg['env'] ?? '') === 'development' ? 'selected' : '' ?>>development</option>
          </select>
        </div>
        <div class="col-md-6"><label class="form-label">App name</label>
          <input class="form-control" name="app_name" value="<?= h($cfg['app_name'] ?? 'TPT Aggregator') ?>"></div>
        <div class="col-md-6"><label class="form-label">Company name</label>
          <input class="form-control" name="company_name" value="<?= h($cfg['company_name'] ?? 'TPT Logistics') ?>"></div>
        <div class="col-12">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" name="https" value="1" id="https" <?= !empty($cfg['https']) ? 'checked' : '' ?>>
            <label class="form-check-label" for="https">Force HTTPS (production sites with SSL)</label>
          </div>
          <div class="form-check mt-2">
            <input class="form-check-input" type="checkbox" name="install_htaccess" value="1" id="install_htaccess" <?= !isset($cfg) || !empty($cfg['install_htaccess']) || !isset($cfg['install_htaccess']) ? 'checked' : '' ?>>
            <label class="form-check-label" for="install_htaccess">
              <strong>Install project-root <code>.htaccess</code></strong>
              — rewrites every request to <code>/public/</code> so visitors hit
              <code>https://your-domain/</code> instead of <code>/public/…</code>.
              Required on most shared hosting where the DocumentRoot is the project folder, not <code>/public/</code>.
            </label>
          </div>
        </div>
      </div>

      <h6 class="mt-4 mb-2 text-muted">First super-admin</h6>
      <div class="row g-3">
        <div class="col-md-6"><label class="form-label">Name</label>
          <input class="form-control" name="admin_name" value="<?= h($cfg['admin_name'] ?? 'System Admin') ?>"></div>
        <div class="col-md-6"><label class="form-label">Email *</label>
          <input class="form-control" type="email" name="admin_email" value="<?= h($cfg['admin_email'] ?? '') ?>" required></div>
        <div class="col-md-6"><label class="form-label">Password *</label>
          <input class="form-control" type="password" name="admin_pass" minlength="8" required>
          <div class="form-text" style="font-size:.78rem;">Min 8 chars. This account is super-admin (lands on /sys, invisible to tenant admins).</div>
        </div>
      </div>

      <h6 class="mt-4 mb-2 text-muted">Initial data</h6>
      <div class="form-check mb-2">
        <input class="form-check-input" type="radio" name="use_dump" value="0" id="freshOpt" <?= empty($cfg['use_dump']) ? 'checked' : '' ?>>
        <label class="form-check-label" for="freshOpt"><strong>Fresh install</strong> — run migrations + seed permissions, email templates, expense categories</label>
      </div>
      <?php if (is_file($DB_DUMP)): ?>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="use_dump" value="1" id="dumpOpt" <?= !empty($cfg['use_dump']) ? 'checked' : '' ?>>
        <label class="form-check-label" for="dumpOpt"><strong>Restore from <code>database.sql</code></strong> — found in project root (<?= number_format(filesize($DB_DUMP) / 1024, 0) ?> KB) — includes the demo dataset and all seeded users</label>
      </div>
      <?php else: ?>
        <p class="text-muted" style="font-size:.85rem;">No <code>database.sql</code> found in project root, so only the fresh-install option is available.</p>
      <?php endif; ?>

      <input type="hidden" name="enc_key" value="<?= h($cfg['enc_key'] ?? gen_encryption_key()) ?>">

      <div class="mt-4 d-flex gap-2">
        <button class="btn btn-primary">Continue →</button>
        <a class="btn btn-light" href="<?= h(url(2)) ?>">← Back</a>
      </div>
    </form>

  <?php elseif ($step === 4): ?>
    <h4>Confirm and install</h4>
    <p class="text-muted">Review and click Install. This may take ~20-60 seconds.</p>
    <table class="table table-sm">
      <tr><th>Base URL</th><td><code><?= h($cfg['baseUrl'] ?? '') ?></code></td></tr>
      <tr><th>Environment</th><td><?= h($cfg['env'] ?? 'production') ?></td></tr>
      <tr><th>Database</th><td><?= h($cfg['db_user'] ?? '') ?>@<?= h($cfg['db_host'] ?? '') ?>:<?= h($cfg['db_port'] ?? '') ?> · <strong><?= h($cfg['db_name'] ?? '') ?></strong> <?= empty($cfg['db_exists']) ? '<small class="text-warning">(will be created)</small>' : '<small class="text-success">(exists)</small>' ?></td></tr>
      <tr><th>Admin</th><td><?= h($cfg['admin_name'] ?? '') ?> &lt;<?= h($cfg['admin_email'] ?? '') ?>&gt;</td></tr>
      <tr><th>Initial data</th><td><?= !empty($cfg['use_dump']) ? 'Restore <code>database.sql</code>' : 'Fresh install (migrations + seeders)' ?></td></tr>
    </table>
    <form method="post" action="<?= h(url(4)) ?>" onsubmit="this.querySelector('button').disabled = true; this.querySelector('button').innerText = 'Installing…';">
      <div class="alert alert-warning" style="font-size:.9rem;">After install, this file will refuse to run again. Delete <code>public/setup.php</code> from the server for maximum safety.</div>
      <button class="btn btn-primary">Install now</button>
      <a class="btn btn-light" href="<?= h(url(3)) ?>">← Back</a>
    </form>

  <?php elseif ($step === 5): ?>
    <?php $log = $_SESSION['install_log'] ?? []; $cfg = $_SESSION['cfg'] ?? []; ?>
    <h4>✅ Installed</h4>
    <p>Your TPT Aggregator install is ready.</p>
    <ul class="mt-3" style="font-size:.92rem;">
      <?php foreach ($log as [$step, $detail]): ?>
        <li><strong><?= h($step) ?></strong><?= $detail ? ' — <span class="text-muted">' . h((string) $detail) . '</span>' : '' ?></li>
      <?php endforeach; ?>
    </ul>
    <hr>
    <p class="mt-3"><strong>Sign in URL:</strong> <a target="_blank" href="<?= h($cfg['baseUrl'] ?? '') ?>login"><?= h($cfg['baseUrl'] ?? '') ?>login</a></p>
    <p><strong>Email:</strong> <code><?= h($cfg['admin_email'] ?? '') ?></code><br>
       <strong>Password:</strong> the one you set in step 3 (super-admin redirects to <code>/sys</code>)</p>

    <div class="alert alert-warning mt-4">
      <strong>Final step — please do this now:</strong>
      <ol class="mb-0">
        <li>Delete <code>public/setup.php</code> from the server.</li>
        <li>Verify <code>writable/.installed</code> exists (lock file).</li>
        <li>If your DB has a different host than 127.0.0.1, edit <code>.env</code> manually.</li>
      </ol>
    </div>
  <?php endif; ?>

  </div></div>

  <p class="text-muted text-center mt-3" style="font-size:.78rem;">TPT Aggregator installer — single-file, no framework boot required for steps 1-3.</p>
</div>
</body></html>
